name: admet_api
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - git=2.49.0=pl5321hc2ff736_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libcurl=8.14.1=h332b0f4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgomp=15.1.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.50.1=hee588c1_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.0=h7b32b05_1
  - pcre2=10.45=hc749103_0
  - perl=5.32.1=7_hd590300_perl5
  - pip=25.1.1=pyh8b19718_0
  - python=3.10.18=hd6af730_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - about-time==4.2.1
      - admet-ai==1.3.1
      - alabaster==1.0.0
      - alive-progress==3.2.0
      - autograd==1.8.0
      - babel==2.17.0
      - blinker==1.9.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - chemfunc==1.0.11
      - chemprop==1.6.1
      - click==8.2.1
      - cloudpickle==3.1.1
      - cma==4.2.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - deprecated==1.2.18
      - descriptastorus==2.8.0
      - dill==0.4.0
      - docstring-parser==0.16
      - docutils==0.21.2
      - fastapi[standard]==0.122.0
      - filelock==3.18.0
      - flask==3.1.1
      - fonttools==4.58.2
      - fsspec==2025.5.1
      - future==1.0.0
      - grapheme==0.6.0
      - hyperopt==0.2.7
      - idna==3.10
      - imagesize==1.4.1
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - packaging==25.0
      - pandas==2.1.4
      - pandas-flavor==0.7.0
      - pillow==11.2.1
      - protobuf==6.31.1
      - psutil==7.0.0
      - py4j==0.10.9.9
      - pygments==2.19.1
      - pymoo==0.6.1.5
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rdkit==2025.3.3
      - requests==2.32.4
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - setuptools==70.0.0
      - six==1.17.0
      - snowballstemmer==3.0.1
      - sphinx==8.1.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sympy==1.14.0
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - tomli==2.2.1
      - torch==2.7.1
      - tqdm==4.67.1
      - triton==3.3.1
      - typed-argument-parser==1.10.1
      - typing-extensions==4.14.0
      - typing-inspect==0.9.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - uvicorn==0.38.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xarray==2025.6.1
      - xgboost==0.81
prefix: /home/nberney/.conda/envs/ml_moo
